### ISSUE TITLE
OneDjango doesn't support ProtectedDatasetViewSet

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/iblalyx#89]
`response = task.register_datasets(default=True)` results in the following error:
```
2024-11-08 15:10:42 INFO     patcher.py:210  1/1 SWC_AY_001_2024-10-22_001, registering 11 files
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/datauser/Documents/PYTHON/ibllib-repo/ibllib/pipes/tasks.py", line 282, in register_datasets
    return self.data_handler.uploadData(self.outputs, self.version, **kwargs)
  File "/home/datauser/Documents/PYTHON/ibllib-repo/ibllib/oneibl/data_handlers.py", line 988, in uploadData
    return sdsc_patcher.patch_datasets(outputs, dry=False, versions=versions, **kwargs)
  File "/home/datauser/Documents/PYTHON/ibllib-repo/ibllib/oneibl/patcher.py", line 617, in patch_datasets
    response = super().patch_datasets(file_list, **kwargs)
  File "/home/datauser/Documents/PYTHON/ibllib-repo/ibllib/oneibl/patcher.py", line 211, in patch_datasets
    responses.extend(self.patch_dataset(_files, **kwargs))
  File "/home/datauser/Documents/PYTHON/ibllib-repo/ibllib/oneibl/patcher.py", line 187, in patch_dataset
    response = ensure_list(self.register_dataset(file_list, dry=dry, **kwargs))
  File "/home/datauser/Documents/PYTHON/ibllib-repo/ibllib/oneibl/patcher.py", line 145, in register_dataset
    return register_dataset(file_list, one=self.one, server_only=True, exists=True, **kwargs)
  File "/home/datauser/Documents/PYTHON/ibllib-repo/ibllib/oneibl/registration.py", line 108, in register_dataset
    protected_status = client.check_protected_files(file_list)
  File "/home/datauser/Documents/PYTHON/ONE/one/registration.py", line 485, in check_protected_files
    records.append(self.one.alyx.get('/check-protected', data=r_, clobber=True))
  File "/home/datauser/Documents/PYTHON/ONE/one/webclient.py", line 905, in get
    rep = self._generic_request(requests.get, rest_query, **kwargs)
  File "/home/datauser/Documents/PYTHON/ONE/one/webclient.py", line 106, in wrapper_decorator
    return method(alyx_client, *args, **kwargs)
  File "/home/datauser/Documents/PYTHON/alyx/alyx/data/management/one_django.py", line 64, in _generic_request
    return fcn(self, partial(self._dispath, reqfunction), rest_query, data, files)
  File "/home/datauser/Documents/PYTHON/ONE/one/webclient.py", line 600, in _generic_request
    r = reqfunction(self.base_url + rest_query,
  File "/home/datauser/Documents/PYTHON/alyx/alyx/data/management/one_django.py", line 134, in _dispath
    view = match.func.view_class.as_view(**match.func.view_initkwargs)
AttributeError: 'function' object has no attribute 'view_class'
```

**Comment by k1o0** [comment]
Done in https://github.com/int-brain-lab/iblalyx/commit/2d585783a2e3dd4df66e995a6c87758596709437
